Raise psr/simple-cache to ^2.0|^3.0 and PHP to ^8.0
yiisoft/cache-redis pull request #10
Opened 2022-10-08 12:01 UTC by dehbka

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️
| Fixed issues  | [5](https://github.com/yiisoft/cache-redis/issues/5)

2022-10-08 12:05 UTC, dehbka commented
Hello, can you add hacktoberfest tag to repo?

2022-10-09 09:19 UTC, vjik commented
> Hello, can you add hacktoberfest tag to repo?

done

2022-10-09 09:28 UTC, vjik requested changes

2022-10-09 09:28 UTC, vjik commented on CHANGELOG.md
> +- Chg: Raise the minimum `psr/simple-cache` version to `^2.0|^3.0` and the minimum PHP version to `^8.0` (@dehbka)
```suggestion
- Chg #5: Raise the minimum `psr/simple-cache` version to `^2.0|^3.0` and the minimum PHP version to `^8.0` (@dehbka)
```

2022-10-09 19:34 UTC, samdark approved these changes

2022-10-11 07:15 UTC, merged